# In addition to this file, load a config file `keys.yml`, where
#  `keys.yml` should contain the following content:
#
#   module: telegramio
#   config:
#     telegram-token: <sexycactus>  # Your telegram token here
#   ---
#   module: ontology
#   config:
#     neo4j_address: bolt://localhost:7687  # Your neo4j server uri here
#     neo4j_username: neo4j                 # Your neo4j user here
#     neo4j_pw: <cornycrab>                 # Your neo4j pw here

---
module: core
config:
  tickrate: 10
  import:
    - ravestate_rawio
    - ravestate_nlp
    - ravestate_telegramio
    - ravestate_conio
    - ravestate_roboyio
    - ravestate_genqa
    - ravestate_hibye
    - ravestate_idle
    - ravestate_interloc
    - ravestate_ontology
    - ravestate_roboyqa
    - ravestate_roboy_ad_demo
    - ravestate_ros2
    - ravestate_stalker
    - ravestate_verbaliser
    # - ravestate_fillers
    # - ravestate_wildtalk

---
module: ad_demo
config:
  ros2-handshake-motion-topic: "/roboy_plexus/ReplayTrajectory"
  handshake-motion-name: "HandshakeMotion"

---
module: genqa
config:
  drqa_server_address: "http://35.246.158.89:5000/"
  roboy_answer_sanity: 1000

---
module: roboyqa
config:
  roboy_node_id: 356

---
module: akinator
config:
  certainty_percentage: 90

---
module: idle
config:
  impatience_threshold: 10.0
  bored_threshold: 1.0

---
module: telegramio
config:
  all_in_one_context: True
